CREATE TABLE TELEFONES (
    ID int NOT NULL AUTO_INCREMENT,
    TEL1DDD int NULL,
    TELEFONE1 int NULL,
    TEL2DDD int NULL,
    TELEFONE2 int NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TIPOS (
    ID int NOT NULL AUTO_INCREMENT,
    DESCRICAO varchar(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ESTADOS (
    ID int NOT NULL AUTO_INCREMENT,
    DESCRICAO varchar(2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CIDADES (
    ID int NOT NULL AUTO_INCREMENT,
    DESCRICAO varchar(150) NOT NULL,
    ESTADO_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS (ID)
);

CREATE TABLE DISTRITOS (
    ID int NOT NULL AUTO_INCREMENT,
    DESCRICAO varchar(150) NOT NULL,
    CIDADE_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES CIDADES (ID)
);

CREATE TABLE BAIRROS (
    ID int NOT NULL AUTO_INCREMENT,
    DESCRICAO varchar(150) NOT NULL,
    DISTRITO_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID)
);

CREATE TABLE ENDERECOS (
    ID int NOT NULL AUTO_INCREMENT,
    ENDERECO varchar(150) NOT NULL,
    NUMERO int NULL,
  	CEP varchar(10) NOT NULL,
  	CIDADE_ID int NOT NULL,
  	ESTADO_ID int NOT NULL,
  	DISTRITO_ID int NOT NULL,
    BAIRRO_ID int NOT NULL,
    LATITUDE DECIMAL(11, 8) NULL,
    LONGITUDE DECIMAL(11, 8) NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CIDADE_ID) REFERENCES CIDADES (ID),
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS (ID),
    FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID),
    FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRROS (ID)
);

CREATE TABLE DIRETORIAS (
    ID int NOT NULL AUTO_INCREMENT,
    NOME varchar(50) NULL,
    DESCRICAO varchar(50) NOT NULL,
    ENDERECO_ID int NULL,
    TELEFONE_ID int NULL,
    EMAIL varchar (200) NULL,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECOS (ID),
    FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONES (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE SUBPREFEITURAS (
    ID int NOT NULL AUTO_INCREMENT,
    NOME varchar(50) NULL,
    DESCRICAO varchar(50) NOT NULL,
    ENDERECO_ID int NULL,
    TELEFONE_ID int NULL,
    EMAIL varchar (200) NULL,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECOS (ID),
    FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONES (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE ESCOLAS (
    ID int NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    TELEFONE_ID int NULL,
    DIRETORIA_ID int NOT NULL,
    SUBPREFEITURA_ID int NOT NULL,
	  ENDERECO_ID int NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ESCOLAS_TIPOS (
    ID int NOT NULL AUTO_INCREMENT,
    ESCOLA_ID int NOT NULL,
    TIPO_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ESCOLA_ID) REFERENCES ESCOLAS (ID),
    FOREIGN KEY (TIPO_ID) REFERENCES TIPOS (ID)
);



insert into TIPOS (DESCRICAO) VALUES ('EMEI');
insert into TIPOS (DESCRICAO) VALUES ('EMEBS');
insert into TIPOS (DESCRICAO) VALUES ('EMEF');
insert into TIPOS (DESCRICAO) VALUES ('CEU');
insert into TIPOS (DESCRICAO) VALUES ('EMEFM');
insert into TIPOS (DESCRICAO) VALUES ('CEI');
insert into TIPOS (DESCRICAO) VALUES ('CEMEI');
insert into TIPOS (DESCRICAO) VALUES ('DIRET');
insert into TIPOS (DESCRICAO) VALUES ('CMCT');
insert into TIPOS (DESCRICAO) VALUES ('CIEJA');
insert into TIPOS (DESCRICAO) VALUES ('CMCT');
insert into TIPOS (DESCRICAO) VALUES ('MOVA');


insert into ESTADOS (DESCRICAO) VALUES ('SP');
insert into ESTADOS (DESCRICAO) VALUES ('RJ');

insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Adamantina', 1);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Adolfo', 1);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Aguaí', 1);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Águas da Prata', 1);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Angra dos Reis', 2);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Aperibé', 2);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Araruama', 2);
insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('Areal', 2);


insert into CIDADES (DESCRICAO, ESTADO_ID) VALUES ('São Paulo', 1);

insert into DISTRITOS (DESCRICAO, CIDADE_ID) VALUES ('São Mateus', 9);
insert into DISTRITOS (DESCRICAO, CIDADE_ID) VALUES ('Guaianases', 9);
insert into DISTRITOS (DESCRICAO, CIDADE_ID) VALUES ('Itaim Paulista', 9);
insert into DISTRITOS (DESCRICAO, CIDADE_ID) VALUES ('Cidade Tiradentes', 9);

insert into BAIRROS (DESCRICAO, DISTRITO_ID) VALUES ('CONJUNTO HABITACIONAL BARRO BRANCO II', 4);

insert into ENDERECOS (ENDERECO, NUMERO, COMPLEMENTO, CEP, CIDADE_ID, ESTADO_ID, DISTRITO_ID, BAIRRO_ID) VALUES ('RUA SALVADOR VIGANO', 100, '', '8473605', 9, 1, 4,1);
